apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: e-webapp
  labels: 
    app: employees
spec:
  scaleTargetRef: 
    apiVersion: apps/v1
    kind: Deployment
    name: e-webapp
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 2
